# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sixthWeek_Assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sixthWeek_Assignment
  pod 'Kingfisher', '~> 5.0' 
  pod 'Alamofire', '~> 5.1' 
end
